version: '3.4'

services:
  rotate-image:
    build: ./backend
    env_file: .env
    command: /bin/sh -c "yarn start"
    ports:
      - '3001:3000'
  frontend:
    build: ./frontend
    env_file: .env
    command: /bin/sh -c "serve"
    ports:
      - '5001:5000'
